param(
    [string]$Location = "westeurope",
    [string]$Environment = "livetest",
    [string]$Owner = "",
    [string]$SubscriptionId = "",
    [switch]$KeepResources,
    [switch]$SkipSmokeTests,
    [switch]$AllowExistingState
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$RunId = Get-Date -Format "yyyyMMdd-HHmmss"
$RunRoot = Join-Path ([System.IO.Path]::GetTempPath()) "ai-lab-live-validation-$RunId"
$LogRoot = Join-Path $RunRoot "logs"
$TfVarsPath = Join-Path $RunRoot "live-validation.tfvars"
$TfPlanPath = Join-Path $RunRoot "ai-lab.tfplan"
$ExerciseRoot = Join-Path $RepoRoot "exercises\python"
$EnvPath = Join-Path $ExerciseRoot ".env"
$EnvBackupPath = Join-Path $RunRoot ".env.backup"
$VenvPath = Join-Path $ExerciseRoot ".venv"
$VenvPython = Join-Path $VenvPath "Scripts\python.exe"
$StatePath = Join-Path $RepoRoot "terraform.tfstate"

New-Item -ItemType Directory -Force -Path $RunRoot, $LogRoot | Out-Null

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "==> $Message"
}

function Invoke-LoggedNative {
    param(
        [string]$Name,
        [string]$FilePath,
        [string[]]$ArgumentList,
        [string]$WorkingDirectory = $RepoRoot
    )

    $safeName = $Name -replace "[^A-Za-z0-9_.-]", "_"
    $logPath = Join-Path $LogRoot "$safeName.log"
    Write-Step $Name
    Push-Location $WorkingDirectory
    try {
        & $FilePath @ArgumentList *>&1 | Tee-Object -FilePath $logPath
        $exitCode = if ($null -eq $LASTEXITCODE) { 0 } else { $LASTEXITCODE }
        if ($exitCode -ne 0) {
            throw "$Name failed with exit code $exitCode. See $logPath"
        }
    }
    finally {
        Pop-Location
    }
}

function Get-NativeOutput {
    param(
        [string]$FilePath,
        [string[]]$ArgumentList,
        [string]$WorkingDirectory = $RepoRoot
    )

    Push-Location $WorkingDirectory
    try {
        $output = & $FilePath @ArgumentList
        $exitCode = if ($null -eq $LASTEXITCODE) { 0 } else { $LASTEXITCODE }
        if ($exitCode -ne 0) {
            throw "$FilePath $($ArgumentList -join ' ') failed with exit code $exitCode"
        }
        return ($output -join "`n")
    }
    finally {
        Pop-Location
    }
}

function Get-TerraformRawOutput {
    param([string]$Name)
    return (Get-NativeOutput -FilePath "terraform" -ArgumentList @("output", "-raw", $Name)).Trim()
}

function Write-ExerciseEnv {
    param([object]$ExerciseEnvironment)

    $lines = @(
        "# Generated by scripts/invoke-live-validation.ps1 on $(Get-Date -Format o).",
        "# Do not commit this file. It contains live validation secrets.",
        "AZURE_AI_SERVICES_ENDPOINT=$($ExerciseEnvironment.AZURE_AI_SERVICES_ENDPOINT)",
        "AZURE_AI_SERVICES_KEY=$(Get-TerraformRawOutput "ai_services_key")",
        "AZURE_AI_SERVICES_REGION=$($ExerciseEnvironment.AZURE_AI_SERVICES_REGION)",
        "CONTENT_SAFETY_ENDPOINT=$($ExerciseEnvironment.CONTENT_SAFETY_ENDPOINT)",
        "CONTENT_SAFETY_KEY=$(Get-TerraformRawOutput "content_safety_key")",
        "AI_SEARCH_ENDPOINT=$($ExerciseEnvironment.AI_SEARCH_ENDPOINT)",
        "AI_SEARCH_KEY=$(Get-TerraformRawOutput "ai_search_admin_key")",
        "AI_SEARCH_INDEX=ai-lab-docs-$RunId",
        "AI_SEARCH_ADVANCED_INDEX=ai-lab-rag-advanced-$RunId",
        "DOCUMENT_INTELLIGENCE_ENDPOINT=$($ExerciseEnvironment.DOCUMENT_INTELLIGENCE_ENDPOINT)",
        "DOCUMENT_INTELLIGENCE_KEY=$(Get-TerraformRawOutput "document_intelligence_key")",
        "DOCUMENT_INTELLIGENCE_SAMPLE_URL=https://raw.githubusercontent.com/Azure-Samples/cognitive-services-REST-api-samples/master/curl/form-recognizer/sample-layout.pdf",
        "VISION_SAMPLE_URL=https://learn.microsoft.com/azure/ai-services/computer-vision/media/quickstarts/presentation.png",
        "AZURE_OPENAI_ENDPOINT=$($ExerciseEnvironment.AZURE_OPENAI_ENDPOINT)",
        "AZURE_OPENAI_KEY=",
        "AZURE_OPENAI_DEPLOYMENT=$($ExerciseEnvironment.AZURE_OPENAI_DEPLOYMENT)",
        "FOUNDRY_HUB_DISCOVERY_URL=$($ExerciseEnvironment.FOUNDRY_HUB_DISCOVERY_URL)",
        "FOUNDRY_PROJECT_ID=$($ExerciseEnvironment.FOUNDRY_PROJECT_ID)",
        "APPLICATIONINSIGHTS_CONNECTION_STRING=$(Get-TerraformRawOutput "application_insights_connection_string")"
    )

    Set-Content -LiteralPath $EnvPath -Value $lines -Encoding UTF8
}

function Remove-GeneratedExerciseArtifacts {
    Get-ChildItem -Path $ExerciseRoot -File -Include "speech-output.wav", "*-output.json", "*-output.jsonl", "*-output.wav" -Recurse |
        Remove-Item -Force -ErrorAction SilentlyContinue
}

if ((Test-Path $StatePath) -and -not $AllowExistingState) {
    throw "terraform.tfstate already exists. Re-run with -AllowExistingState only if this state belongs to the disposable live validation run."
}

if ($SubscriptionId) {
    Invoke-LoggedNative -Name "az account set" -FilePath "az" -ArgumentList @("account", "set", "--subscription", $SubscriptionId)
}

$account = Get-NativeOutput -FilePath "az" -ArgumentList @("account", "show", "-o", "json") | ConvertFrom-Json
if (-not $Owner) {
    $Owner = $account.user.name
}

$hadEnv = Test-Path $EnvPath
if ($hadEnv) {
    Copy-Item -LiteralPath $EnvPath -Destination $EnvBackupPath -Force
}

$shouldDestroy = $false
$destroySucceeded = $false
$resourceGroupName = ""

$tfvars = @"
ctx = {
  project     = "ailab"
  location    = "$Location"
  environment = "$Environment"
  owner       = "$Owner"
  tags = {
    CostCenter = "LiveValidation"
    Purpose    = "Extended AI Lab live validation"
  }
}

deploy_ai_services              = true
deploy_content_safety           = true
deploy_ai_search                = true
deploy_document_intelligence    = true
deploy_azure_openai             = false
deploy_ai_foundry               = false
deploy_app_hosting              = true
deploy_private_networking       = false
deploy_observability_alerts     = true
store_service_keys_in_key_vault = true
grant_deployer_key_vault_secret_permissions = true

enable_public_network_access      = true
enable_foundry_project_management = true

ai_services_sku_name = "S0"
content_safety_sku_name = "S0"
ai_search_sku = "free"
ai_search_semantic_search_sku = ""
document_intelligence_sku_name = "S0"
observability_total_calls_threshold = 100
"@

Set-Content -LiteralPath $TfVarsPath -Value $tfvars -Encoding UTF8

try {
    Invoke-LoggedNative -Name "terraform fmt check" -FilePath "terraform" -ArgumentList @("fmt", "-check", "-recursive")
    Invoke-LoggedNative -Name "terraform init" -FilePath "terraform" -ArgumentList @("init")
    Invoke-LoggedNative -Name "terraform validate" -FilePath "terraform" -ArgumentList @("validate")

    if (-not (Test-Path $VenvPython)) {
        Invoke-LoggedNative -Name "python venv create" -FilePath "python" -ArgumentList @("-m", "venv", $VenvPath)
    }
    Invoke-LoggedNative -Name "python install requirements" -FilePath $VenvPython -ArgumentList @("-m", "pip", "install", "-r", "exercises\python\requirements.txt")
    Invoke-LoggedNative -Name "python unit tests" -FilePath $VenvPython -ArgumentList @("-m", "pytest", "tests\python")
    Invoke-LoggedNative -Name "repo quality checks" -FilePath "python" -ArgumentList @("scripts\check_lab_quality.py")
    Invoke-LoggedNative -Name "go skip-safe tests" -FilePath "go" -ArgumentList @("test", "./...") -WorkingDirectory (Join-Path $RepoRoot "tests")

    Invoke-LoggedNative -Name "terraform plan" -FilePath "terraform" -ArgumentList @("plan", "-var-file=$TfVarsPath", "-out=$TfPlanPath")
    $shouldDestroy = $true
    Invoke-LoggedNative -Name "terraform apply" -FilePath "terraform" -ArgumentList @("apply", $TfPlanPath)

    $resourceGroupName = Get-TerraformRawOutput "resource_group_name"
    $exerciseEnvironment = Get-NativeOutput -FilePath "terraform" -ArgumentList @("output", "-json", "exercise_environment") | ConvertFrom-Json
    Write-ExerciseEnv -ExerciseEnvironment $exerciseEnvironment

    $previousSubscription = $env:ARM_SUBSCRIPTION_ID
    $previousResourceGroup = $env:AI_LAB_RESOURCE_GROUP
    try {
        $env:ARM_SUBSCRIPTION_ID = $account.id
        $env:AI_LAB_RESOURCE_GROUP = $resourceGroupName
        Invoke-LoggedNative -Name "go live resource group tests" -FilePath "go" -ArgumentList @("test", "./...") -WorkingDirectory (Join-Path $RepoRoot "tests")
    }
    finally {
        $env:ARM_SUBSCRIPTION_ID = $previousSubscription
        $env:AI_LAB_RESOURCE_GROUP = $previousResourceGroup
    }

    if (-not $SkipSmokeTests) {
        $smokeScripts = @(
            "00_setup_check.py",
            "01_language_sentiment.py",
            "02_language_pii_entities.py",
            "03_vision_ocr.py",
            "04_speech_basics.py",
            "05_translator.py",
            "06_content_safety.py",
            "07_search_rag_optional.py",
            "08_search_rag_advanced.py",
            "09_document_intelligence_layout.py",
            "10_vision_image_analysis.py",
            "11_content_safety_guardrails.py",
            "12_speech_pronunciation_assessment.py",
            "13_foundry_agent_blueprint.py",
            "14_observability_evaluation.py"
        )

        foreach ($script in $smokeScripts) {
            Invoke-LoggedNative -Name "smoke $script" -FilePath $VenvPython -ArgumentList @((Join-Path "exercises\python" $script))
        }
    }
}
finally {
    if (-not $KeepResources -and $shouldDestroy) {
        try {
            Invoke-LoggedNative -Name "terraform destroy" -FilePath "terraform" -ArgumentList @("destroy", "-auto-approve", "-var-file=$TfVarsPath")

            if ($resourceGroupName) {
                $exists = (Get-NativeOutput -FilePath "az" -ArgumentList @("group", "exists", "--name", $resourceGroupName)).Trim()
                if ($exists -ne "false") {
                    throw "Resource group $resourceGroupName still exists after destroy."
                }
            }

            $stateList = (Get-NativeOutput -FilePath "terraform" -ArgumentList @("state", "list")).Trim()
            if ($stateList) {
                throw "Terraform state is not empty after destroy: $stateList"
            }

            $destroySucceeded = $true
            Remove-Item -LiteralPath (Join-Path $RepoRoot "terraform.tfstate"), (Join-Path $RepoRoot "terraform.tfstate.backup") -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path $RepoRoot -Filter "*.tfplan" -File | Remove-Item -Force -ErrorAction SilentlyContinue
        }
        finally {
            if ($hadEnv) {
                Copy-Item -LiteralPath $EnvBackupPath -Destination $EnvPath -Force
            }
            elseif (Test-Path $EnvPath) {
                Remove-Item -LiteralPath $EnvPath -Force
            }

            Remove-GeneratedExerciseArtifacts
        }
    }
}

Write-Host ""
Write-Host "Live validation logs: $LogRoot"
if ($KeepResources) {
    Write-Host "Resources were kept because -KeepResources was set."
}
elseif ($destroySucceeded) {
    Write-Host "Live validation completed and resources were destroyed."
}
